### ISSUE TITLE
Server Crash [1.16] Issue Title

### ISSUE THREAD

**Issue by SLSpicy** [InnovativeOnlineIndustries/Industrial-Foregoing#1013]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**

Crash Log:

---- Minecraft Crash Report ----
// Don't do that.

Time: 2/10/21 10:06 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at com.buuz135.industrial.capability.BackpackCapabilityProvider.getCapability(BackpackCapabilityProvider.java:54) ~[?:3.2.8.2] {re:classloading}
at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:102) ~[?:?] {re:classloading}
at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
at thetadev.constructionwand.containers.handlers.HandlerCapability.matches(HandlerCapability.java:17) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.containers.ContainerManager.countItems(ContainerManager.java:22) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.countItem(WandJob.java:164) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.addBlockItem(WandJob.java:102) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.addBlockItems(WandJob.java:130) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.<init>(WandJob.java:66) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.ConstructionJob.<init>(ConstructionJob.java:18) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.getJob(WandJob.java:90) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.client.RenderBlockPreview.renderBlockHighlight(RenderBlockPreview.java:45) ~[?:1.16.2-1.7] {re:classloading}
at net.minecraftforge.eventbus.ASMEventHandler_398_RenderBlockPreview_renderBlockHighlight_DrawHighlightEvent.invoke(.dynamic) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:143) ~[?:?] {re:classloading}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.optifine.reflect.Reflector.callBoolean(Reflector.java:743) ~[?:?] {re:classloading}
at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1921) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld}
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld}
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1553646796.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at com.buuz135.industrial.capability.BackpackCapabilityProvider.getCapability(BackpackCapabilityProvider.java:54) ~[?:3.2.8.2] {re:classloading}
at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:102) ~[?:?] {re:classloading}
at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
at thetadev.constructionwand.containers.handlers.HandlerCapability.matches(HandlerCapability.java:17) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.containers.ContainerManager.countItems(ContainerManager.java:22) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.countItem(WandJob.java:164) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.addBlockItem(WandJob.java:102) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.addBlockItems(WandJob.java:130) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.<init>(WandJob.java:66) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.ConstructionJob.<init>(ConstructionJob.java:18) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.job.WandJob.getJob(WandJob.java:90) ~[?:1.16.2-1.7] {re:classloading}
at thetadev.constructionwand.client.RenderBlockPreview.renderBlockHighlight(RenderBlockPreview.java:45) ~[?:1.16.2-1.7] {re:classloading}
at net.minecraftforge.eventbus.ASMEventHandler_398_RenderBlockPreview_renderBlockHighlight_DrawHighlightEvent.invoke(.dynamic) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:143) ~[?:?] {re:classloading}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.optifine.reflect.Reflector.callBoolean(Reflector.java:743) ~[?:?] {re:classloading}
at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1921) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld}
-- Affected level --
Details:
All players: 1 total; [ClientPlayerEntity['SL_Spicy'/3703, l='ClientLevel', x=-116.01, y=58.00, z=-25.74]]
Chunk stats: Client Chunk Cache: 361, 204
Level dimension: minecraft:overworld
Level spawn location: World: (-16,69,-64), Chunk: (at 0,4,0 in -1,-4; contains blocks -16,0,-64 to -1,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Level time: 26995810 game time, 29116958 day time
Server brand: forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass}
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1553646796.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
Minecraft Version: 1.16.4
Minecraft Version ID: 1.16.4
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 808113264 bytes (770 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
CPUs: 20
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
ModLauncher: 8.0.6+85+master.325de55
ModLauncher launch target: fmlclient
ModLauncher naming: srg
ModLauncher services:
/mixin-0.8.2.jar mixin PLUGINSERVICE
/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE
/forge-1.16.4-35.1.36.jar object_holder_definalize PLUGINSERVICE
/forge-1.16.4-35.1.36.jar runtime_enum_extender PLUGINSERVICE
/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE
/forge-1.16.4-35.1.36.jar capability_inject_definalize PLUGINSERVICE
/forge-1.16.4-35.1.36.jar runtimedistcleaner PLUGINSERVICE
/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE
/OptiFine_1.16.4_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE
/forge-1.16.4-35.1.36.jar fml TRANSFORMATIONSERVICE
FML: 35.1
Forge: net.minecraftforge:35.1.36
FML Language Providers:
javafml@35.1
minecraft@1
Mod List:
forge-1.16.4-35.1.36-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
industrial-foregoing-1.16.4-3.2.8.2-6b5c95b.jar   |Industrial Foregoing          |industrialforegoing           |3.2.8.2             |DONE      |NOSIGNATURE
repurposed_structures-1.16.4-2.3.4.jar            |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.4        |DONE      |NOSIGNATURE
DungeonsMod-1.16.3-1.1.18.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.1.18       |DONE      |NOSIGNATURE
titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |DONE      |NOSIGNATURE
cucumber-1.16.4-4.1.5.jar                         |Cucumber Library              |cucumber                      |4.1.5               |DONE      |NOSIGNATURE
morevanillalib-1.16.4-1.3.9.jar                   |MoreVanillaLib                |morevanillalib                |1.3.9               |DONE      |NOSIGNATURE
BiomesOPlenty-1.16.4-13.0.0.430-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.430   |DONE      |NOSIGNATURE
valkyrielib-1.16.4-3.0.6.1.jar                    |ValkyrieLib                   |valkyrielib                   |3.0.6.1             |DONE      |NOSIGNATURE
ironfurnaces-1.16.5-2.6.1.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.1               |DONE      |NOSIGNATURE
craftingstation-4.1.1.jar                         |Crafting Station              |craftingstation               |4.1.1               |DONE      |NOSIGNATURE
jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
FunMod 5.1.jar                                    |Fun Mod                       |funmod                        |5.1                 |DONE      |NOSIGNATURE
mekanism-1.16.4-10.0.18.445.jar                   |Mekanism                      |mekanism                      |10.0.18             |DONE      |NOSIGNATURE
jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
portality-1.16.4-3.2.0.jar                        |Portality                     |portality                     |3.2.0               |DONE      |NOSIGNATURE
curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |DONE      |NOSIGNATURE
patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
Neat 1.7-26.jar                                   |Neat                          |neat                          |1.7-26              |DONE      |NOSIGNATURE
Xaeros_Minimap_21.3.0.1_Forge_1.16.5.jar          |Xaero's Minimap               |xaerominimap                  |21.3.0              |DONE      |NOSIGNATURE
CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |NOSIGNATURE
citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
appliedenergistics2-8.2.0-beta.3.jar              |Applied Energistics 2         |appliedenergistics2           |8.2.0-beta.3        |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
vanillahammers-1.16.4-2.2.0.jar                   |Vanilla Hammers               |vanillahammers                |2.2.0               |DONE      |NOSIGNATURE
elevatorid-1.16.5-1.7.12.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.12       |DONE      |NOSIGNATURE
upstream-1.0.jar                                  |Upstream                      |upstream                      |1.0                 |DONE      |NOSIGNATURE
champions-forge-1.16.5-2.0.1.0.jar                |Champions                     |champions                     |1.16.5-2.0.1.0      |DONE      |NOSIGNATURE
mutantbeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
constructionwand-1.16.2-1.7.jar                   |Construction Wand             |constructionwand              |1.16.2-1.7          |DONE      |NOSIGNATURE
iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |DONE      |NOSIGNATURE
trashcans-1.0.6a-mc1.16.4.jar                     |Trash Cans                    |trashcans                     |1.0.6a              |DONE      |NOSIGNATURE
byg-1.1.7-BETA-v3.jar                             |Oh The Biomes You'll Go       |byg                           |1.1.7-BETA-v3       |DONE      |NOSIGNATURE
forge-1.16.4-35.1.36-universal.jar                |Forge                         |forge                         |35.1.36             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
betterendforge-1.16.4-1.4.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.4.0        |DONE      |NOSIGNATURE
PrettyPipes-1.9.1.jar                             |Pretty Pipes                  |prettypipes                   |1.9.1               |DONE      |NOSIGNATURE
structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
mysticalagriculture-1.16.4-4.1.4.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.4               |DONE      |NOSIGNATURE
ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |NOSIGNATURE
BetterAdvancements-1.16.4-0.1.0.104.jar           |Better Advancements           |betteradvancements            |0.1.0.104           |DONE      |NOSIGNATURE
Crash Report UUID: c9eae199-b243-438c-8dbf-259240cedfc7
Patchouli open book context: n/a
Launched Version: 1.16.4-forge-35.1.36
Backend library: LWJGL version 3.2.2 build 10
Backend API: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
GL Caps: Using framebuffer using OpenGL 3.0
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'forge'
Type: Client (map_client.txt)
Graphics mode: fancy
Resource Packs: vanilla, mod_resources, file/FaithfulPBR_256x_2.4p
Current Language: English (US)
CPU: 20x Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz
OptiFine Version: OptiFine_1.16.4_HD_U_G6
OptiFine Build: 20210117-001622
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: SEUS-Renewed-v1.0.1
OpenGlVersion: 4.6.0 NVIDIA 456.71
OpenGlRenderer: GeForce RTX 2080 SUPER/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 20

**Comment by Buuz135** [comment]
Update the mods, and follow the template

**Comment by SLSpicy** [comment]
does the updated version work with 1.16.4? that is the version the server
is on

**Comment by Buuz135** [comment]
No, update your forge

**Comment by SLSpicy** [comment]
I've updated my forge and am still having this issue.
https://pastebin.com/AbVhnQcc
