### ISSUE TITLE
Server Crash with the potion_brewer

### ISSUE THREAD

**Issue by Profstar** [InnovativeOnlineIndustries/Industrial-Foregoing#1131]
Sorry for my English. I came from Germany.
When the Potion Brewer make the last recipe for the "lingering_potion direct_damage II" then the Server Crash with a "ticking Tile" Error. The Brewer NOT USE the Water in his Slot. (Is Infinty)
To Reproduce the Error go following steps:

Power the Brewer, feed with Blaze Powder, Glassbottles in the Slot and 1 Bucket of Water.
Add Incredence in following Order in the top Slot:
1. Netherwart
2. glistering_melon_slice
3. fermented_spider_eye
4. gunpowder
5. Glowstone Powder
6.  dragon_breath

The first 5 Steps works perfected. When the last Step ENDS, then the Server Crash. (It crash EVER when make, HOPPER below the Brewer remove the water-bottle on the Brewer, NOT the Potion) Help for this is only kill the issue with FORGE CONFIG! You must the Server run ONCE with the "removeErroringTileEntities = true" command in the "forge.cfg" File.
This command remove the entire Inventory of the Brewer, but the Brewer is still working.
I have NOT tested with other Potions.

**Industrial Foregoing Version:**
Version 1.16.5-3.2.11-55cb112

**Titanium Version:**
Version 1.16.5-3.2.8.2

**Crashlog If Applicable (Upload to pastebin/gist):**

---- Minecraft Crash Report ----

Description: Ticking block entity

java.lang.RuntimeException: **Slot 6 not in valid range - [0,6)**
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[forge:?] {re:classloading}
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[forge:?] {re:classloading}
	at com.buuz135.industrial.block.resourceproduction.tile.PotionBrewerTile.canBrew(PotionBrewerTile.java:183) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.buuz135.industrial.block.resourceproduction.tile.PotionBrewerTile.canIncrease(PotionBrewerTile.java:140) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialProcessingTile.lambda$new$2(IndustrialProcessingTile.java:78) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:36) ~[titanium:3.2.8.2] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.func_73660_a(ActiveTile.java:222) ~[titanium:3.2.8.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[forge:?] {re:classloading}
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[forge:?] {re:classloading}
	at com.buuz135.industrial.block.resourceproduction.tile.**PotionBrewerTile.canBrew(PotionBrewerTile.java:183)** ~[industrialforegoing:3.2.11] {re:classloading}
	at com.buuz135.industrial.block.resourceproduction.tile.**PotionBrewerTile.canIncrease(PotionBrewerTile.java:140)** ~[industrialforegoing:3.2.11] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialProcessingTile.lambda$new$2(IndustrialProcessingTile.java:78) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:36) ~[titanium:3.2.8.2] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.func_73660_a(ActiveTile.java:222) ~[titanium:3.2.8.2] {re:classloading}
-- Block entity being ticked --
Details:
	Name: industrialforegoing:potion_brewer // com.buuz135.industrial.block.resourceproduction.tile.PotionBrewerTile
	Block: Block{industrialforegoing:potion_brewer}[subfacing=east]
	Block location: World: (6,146,10), Chunk: (at 6,9,10 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{industrialforegoing:potion_brewer}[subfacing=east]
	Block location: World: (6,146,10), Chunk: (at 6,9,10 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Buuz135** [comment]
Try updating Industrial Foregoing
