### ISSUE TITLE
[1.21] Setting Output Slot of Hydroponic Bed Resulting in Server Stuck

### ISSUE THREAD

**Issue by cc004** [InnovativeOnlineIndustries/Industrial-Foregoing#1511]
When hydroponic beds are connected to each other, trying to set one hydroponic bed to push its output to another will cause the server to stuck.

**Industrial Foregoing Version:** 1.21-3.6.19

**Titanium Version:**4.0.27

**Crashlog If Applicable (Upload to pastebin/gist):**

'''
java.lang.Error: ServerHangWatchdog detected that a single server tick took 180000304.00 seconds (should be max 0.05)
	at java.base/java.util.IdentityHashMap.get(IdentityHashMap.java:342) ~[?:?] {}
	at java.base/java.util.Map.getOrDefault(Map.java:691) ~[?:?] {re:mixin}
	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.capabilities.ItemCapability.getCapability(ItemCapability.java:99) ~[neoforge-21.1.74-universal.jar%23466!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.common.extensions.IItemStackExtension.getCapability(IItemStackExtension.java:494) ~[neoforge-21.1.74-universal.jar%23466!/:?] {re:computing_frames,re:mixin,re:classloading}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.bundle.TankInteractionBundle.lambda$new$1(TankInteractionBundle.java:58) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.bundle.TankInteractionBundle$$Lambda/0x00000000865e5bb8.test(Unknown Source) ~[?:?] {}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.MultiInventoryComponent$MultiInvCapabilityHandler.insertItem(MultiInventoryComponent.java:143) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.isValidForAnySlot(SidedInventoryComponent.java:226) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.transfer(SidedInventoryComponent.java:212) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.workSides(SidedInventoryComponent.java:128) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.work(SidedInventoryComponent.java:139) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:231) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/industrialforegoing@1.21-3.6.19/com.buuz135.industrial.block.agriculturehusbandry.tile.HydroponicBedTile.serverTick(HydroponicBedTile.java:174) ~[industrialforegoing-1.21-3.6.19.jar%23615!/:?] {re:classloading}
	at TRANSFORMER/industrialforegoing@1.21-3.6.19/com.buuz135.industrial.block.agriculturehusbandry.tile.HydroponicBedTile.serverTick(HydroponicBedTile.java:41) ~[industrialforegoing-1.21-3.6.19.jar%23615!/:?] {re:classloading}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$5(BasicTileBlock.java:83) ~[titanium-1.21-4.0.27.jar%23777!/:4.0.27] {re:classloading}
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.block.BasicTileBlock$$Lambda/0x00000000865f43c0.tick(Unknown Source) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:706) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polymorph.mixins.json:MixinLevelChunk from mod polymorph,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:783) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.redirect$bmj000$observable$redirectTick(Level.java:2318) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:LevelMixin from mod mffs,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:LevelMixin from mod observable,pl:mixin:APP:kubejs.mixins.json:LevelMixin from mod kubejs,pl:mixin:APP:xycraft_core.mixins.json:LevelRainShieldMixin from mod xycraft_core,pl:mixin:APP:the_bumblezone-common.mixins.json:world.LevelMixin from mod the_bumblezone,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:LevelMixin from mod mffs,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:LevelMixin from mod observable,pl:mixin:APP:kubejs.mixins.json:LevelMixin from mod kubejs,pl:mixin:APP:xycraft_core.mixins.json:LevelRainShieldMixin from mod xycraft_core,pl:mixin:APP:the_bumblezone-common.mixins.json:world.LevelMixin from mod the_bumblezone,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:428) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:eternal_starlight-common.mixins.json:ServerLevelMixin from mod eternal_starlight,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:the_bumblezone-common.mixins.json:world.ServerWorldMixin from mod the_bumblezone,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin from mod immersiveengineering,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel from mod ohthetreesyoullgrow,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel from mod corgilib,pl:mixin:APP:polymorph.mixins.json:MixinServerLevel from mod polymorph,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:APP:refurbished_furniture.common.mixins.json:ServerLevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:ServerLevelMixin from mod observable,pl:mixin:APP:kubejs.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin from mod ars_elemental,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,re:classloading,pl:mixin:APP:resourcefulconfig.mixins.json:common.DedicatedServerAccessor from mod resourcefulconfig,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin from mod lithostitched,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer from mod nochatreports,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin from mod tombstone,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer$$Lambda/0x000000008636a878.run(Unknown Source) ~[?:?] {}
	at java.base/java.lang.Thread.runWith(Thread.java:1596) [?:?] {re:mixin}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

"Server thread" prio=8 Id=100 RUNNABLE
	at java.base@21.0.5/java.util.IdentityHashMap.get(IdentityHashMap.java:342)
	at java.base@21.0.5/java.util.Map.getOrDefault(Map.java:691)
	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.capabilities.ItemCapability.getCapability(ItemCapability.java:99)
	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.common.extensions.IItemStackExtension.getCapability(IItemStackExtension.java:494)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.bundle.TankInteractionBundle.lambda$new$1(TankInteractionBundle.java:58)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.bundle.TankInteractionBundle$$Lambda/0x00000000865e5bb8.test(Unknown Source)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.MultiInventoryComponent$MultiInvCapabilityHandler.insertItem(MultiInventoryComponent.java:143)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.isValidForAnySlot(SidedInventoryComponent.java:226)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.transfer(SidedInventoryComponent.java:212)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.workSides(SidedInventoryComponent.java:128)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.component.inventory.SidedInventoryComponent.work(SidedInventoryComponent.java:139)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:231)
	at TRANSFORMER/industrialforegoing@1.21-3.6.19/com.buuz135.industrial.block.agriculturehusbandry.tile.HydroponicBedTile.serverTick(HydroponicBedTile.java:174)
	at TRANSFORMER/industrialforegoing@1.21-3.6.19/com.buuz135.industrial.block.agriculturehusbandry.tile.HydroponicBedTile.serverTick(HydroponicBedTile.java:41)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$5(BasicTileBlock.java:83)
	at TRANSFORMER/titanium@4.0.27/com.hrznstudio.titanium.block.BasicTileBlock$$Lambda/0x00000000865f43c0.tick(Unknown Source)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:706)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:783)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.redirect$bmj000$observable$redirectTick(Level.java:2318)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:428)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer$$Lambda/0x000000008636a878.run(Unknown Source)
	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)

'''

**Comment by Buuz135** [comment]
Update titanium
