### ISSUE TITLE
[1.12] NullPointerException in Fluid Pump

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#626]
**Industrial Foregoing Version: **
industrialforegoing-1.12.2-1.12.13-237
**TeslaCoreLib Version: **
tesla-core-lib-1.12.2-1.0.15
**Crashlog If Applicable (Upload to pastebin/gist): **
https://paste.feed-the-beast.com/view/1447a695
https://paste.feed-the-beast.com/view/e0213be3

From FTBTeam/FTB-Academy/issues/222

**Comment by Spongman** [comment]
I just got the same, placing a lava source block within the range of a fluid pump:

````
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at com.buuz135.industrial.tile.world.FluidPumpTile.work(FluidPumpTile.java:101) ~[FluidPumpTile.class:?]
        at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112) ~[WorkingAreaElectricMachine.class:?]
        at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280) ~[ElectricMachine.class:?]
        at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120) ~[CustomElectricMachine.class:?]
        at com.buuz135.industrial.tile.world.FluidPumpTile.protectedUpdate(FluidPumpTile.java:76) ~[FluidPumpTile.class:?]
        at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118) ~[ElectricTileEntity.class:?]
        at net.ndrei.teslacorelib.tileentities.SidedTileEntity.update(SidedTileEntity.kt:991) ~[SidedTileEntity.class:?]
        at net.minecraft.world.World.redirect$tileEntityUpdate$zzj000(World.java:4137) ~[amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1838) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more

````

**Comment by Trnrr** [comment]
Also getting this, I think its the same thing. The log above is the same as what my clients get. On the server it displays this https://gist.githubusercontent.com/Trnrr/83cab767c1a7264af961f348ea5d503a/raw/51e7ffda3ab18807fb5fab4a70cd576d7bed49fe/gistfile1.txt and doesn't allow them to connect.

**Comment by jxu** [comment]
[crash-2020-01-10_20.34.57-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4048832/crash-2020-01-10_20.34.57-server.txt) when placing Crude Oil bucket

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
