### ISSUE TITLE
Tesselating Block Model crash in Minecraft 1.14.4

### ISSUE THREAD

**Issue by Cowllum** [InnovativeOnlineIndustries/Industrial-Foregoing#723]
Industrial Foregoing Version: 1.14.4 (ver. 2.1.2)
Titanium Version: 1.14.4 (ver. 2.2.1.0)
Crashlog: ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/6/20 12:43 AM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at com.buuz135.industrial.proxy.client.model.ConveyorBlockModel.getQuads(ConveyorBlockModel.java:74) ~[?:2.1.2] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:385) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:229) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_215320_a(WorldRenderer.java:1397) ~[?:?] {re:mixin,re:classloading,xf:fml:journeymap:WorldRenderer.markForRerender,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:1145) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1030) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:790) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.0.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$466/1088327571.call(Unknown Source) [forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.buuz135.industrial.proxy.client.model.ConveyorBlockModel.getQuads(ConveyorBlockModel.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88)

-- Block model being tesselated --
Details:
	Block: Block{industrialforegoing:conveyor}[facing=west,sides=none,type=flat,waterlogged=false]
	Block location: World: (-125,52,153), Chunk: (at 3,3,9 in -8,9; contains blocks -128,0,144 to -113,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95)

-- Block being tesselated --
Details:
	Block: Block{industrialforegoing:conveyor}[facing=west,sides=none,type=flat,waterlogged=false]
	Block location: World: (-125,52,153), Chunk: (at 3,3,9 in -8,9; contains blocks -128,0,144 to -113,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89)
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69)
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30)
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102)
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015)
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:385)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:229)
	at net.minecraft.client.renderer.WorldRenderer.func_215320_a(WorldRenderer.java:1397)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:1145)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1030)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Cowl1um'/3721, l='MpServer', x=-122.83, y=52.00, z=152.83]]
	Chunk stats: ImmPortal Client Chunk 225
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,52,144), Chunk: (at 0,3,0 in 0,9; contains blocks 0,0,144 to 15,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 21788 game time, 50789 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$466/1088327571.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1320591080 bytes (1259 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		followingvillagers-1.14.4-1.2.0.jar Following Villagers {followingvillagers@1.14.4-1.2.0 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		pamhc2trees-1.14.4-1.0.0.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		mining-helmet-1.14.4-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		DoggyTalents-1.14.4-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		Neat+1.5-19.jar Neat {neat@1.5-19 DONE}
		Clumps-4.0.1.jar Clumps {clumps@4.0.1 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		tumbleweed-1.14-0.4.7.jar Tumbleweed {tumbleweed@1.14-0.4.7 DONE}
		NaturesCompass-1.14.4-1.8.5.jar Nature's Compass {naturescompass@1.14.4-1.8.5 DONE}
		DungeonCrawl-1.14.4-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		MutantBeasts-1.14.4-1.0.0.jar Mutant Beasts {mutantbeasts@1.14.4-1.0.0 DONE}
		Bookshelf-1.14.4-4.4.71.jar Bookshelf {bookshelf@4.4.71 DONE}
		Reliquary-1.14.4-1.3.4.947.jar Reliquary {xreliquary@1.14.4-1.3.4.947 DONE}
		ForgivingVoid_1.14.4-3.0.8.jar Forgiving Void {forgivingvoid@3.0.8 DONE}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		CarryOn+MC1.14.4+v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		immersive-portals-0.15(for+mc+1.14+with+forge).jar Immersive Portals {immersive_portals@0.15 DONE}
		bsc_1.14-1.0.jar Better Spawner Control {bsc@1.0 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		ruins-1.14.4.6.jar Ruins {ruins@1.14.4.6 DONE}
		mshrtw_1.14.4-1.0.jar Mooshroom Tweaks {mshrtw@1.0 DONE}
		MysticalAgriculture-1.14.4-2.0.6.jar Mystical Agriculture {mysticalagriculture@2.0.6 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		nm_1.14-1.0.jar Nutritious Milk {nm@1.0 DONE}
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		luckyblock-1.14.4-7.9.1.jar Lucky Block {lucky@7.9.1 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		pamhc2crops-1.14.4-1.0.4.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		fishingreal-1.1.jar Fishing Real {fishingreal@1.1 DONE}
		Bountiful-1.14.4-3.1.0.jar Bountiful {bountiful@1.14.4-3.1.0 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		pamhc2foodcore-1.14.4-1.0.2.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.15.3.jar Gravestone Mod {gravestone@1.15.3 DONE}
		ClothConfig2-1.4.1.jar Cloth Config Forge v2 API {cloth-config2@1.4.1 DONE}
		backpacked-1.4.0-mc1.14.4.jar Backpacked {backpacked@1.4.0 DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		filters-1.1.1-1.14.4.jar Filters {filters@1.1.1 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		BetterBurning-1.14.4-1.0.1.jar BetterBurning {betterburning@1.0.1 DONE}
		Charm-1.14.4-1.5.4.jar Charm {charm@1.14.4-1.5.4 DONE}
		BetterFoliage-2.5.0-Forge-1.14.4.jar Better Foliage {betterfoliage@2.5.0 DONE}
		farlanders-1.14.4-1.1.2.jar The Farlanders {farlanders@1.1.2 DONE}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 DONE}
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8300 Eight-Core Processor 
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Buuz135** [comment]
Update to 1.15, 1.14 is no longer mantained
