### ISSUE TITLE
Fluid pump crashes server when two are working in same area

### ISSUE THREAD

**Issue by quasarea** [InnovativeOnlineIndustries/Industrial-Foregoing#743]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): none

When two pumps (emerald range upgrade, speed I, II, and efficiency I) work in the same chunk, game seems to crash (possibly when they try to pump same tile?)

```
[16:18:43] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at com.buuz135.industrial.tile.world.FluidPumpTile.work(FluidPumpTile.java:101) ~[FluidPumpTile.class:?]
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112) ~[WorkingAreaElectricMachine.class:?]
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280) ~[ElectricMachine.class:?]
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120) ~[CustomElectricMachine.class:?]
	at com.buuz135.industrial.tile.world.FluidPumpTile.protectedUpdate(FluidPumpTile.java:76) ~[FluidPumpTile.class:?]
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118) ~[ElectricTileEntity.class:?]
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:991) ~[SidedTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[16:18:43] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: E:\FTB-UR-Server-1.9.0\.\crash-reports\crash-2020-05-04_16.18.43-server.txt
[16:18:43] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```
Attached crash report:
[crash-2020-05-04_16.18.43-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4575529/crash-2020-05-04_16.18.43-server.txt)

**Comment by ProsperCraft** [comment]
I can confirm that our server crashed for the same reason, the player had two pumps in the same area-

Modpack- https://www.curseforge.com/minecraft/modpacks/towncraft

Crashlog- https://gist.github.com/ProsperCraft/d20132bdb7f6cc07e8a8b212b4fed9e5

**Comment by JW6677** [comment]
Having the same issue, instantly crashing the server when 2 pumps are in the same area. Please fix this it's super annoying and I have to reset the nether everytime.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by fabm3n** [comment]
Can you provide a list of support versions in the readme file? That would be helpful.
