### ISSUE TITLE
Random crashes when using NEI to add recipes to the crafter

### ISSUE THREAD

**Issue by xorinzor** [InnovativeOnlineIndustries/Industrial-Foregoing#753]
At random moments when quickly adding recipes from NEI to the crafter in refined storage the server will crash with the same error in the crashlog below.

Relevant line: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.15/src/main/java/com/buuz135/industrial/block/MachineFrameBlock.java#L60

Industrial Foregoing Version: 1.15.2-2.2.2-28d4a81
TeslaCoreLib Version: Unknown?
Crashlog (If Any):

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/7/20 11:07 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.item.ItemGroup.func_78024_c()Ljava/lang/String;
	at com.buuz135.industrial.block.MachineFrameBlock$MachineFrameItem.getCreatorModId(MachineFrameBlock.java:60) ~[?:2.2.2] {re:classloading}
	at vazkii.akashictome.MorphingHandler.getModFromStack(MorphingHandler.java:87) ~[?:1.3-13] {re:classloading}
	at vazkii.akashictome.AttachementRecipe.isTarget(AttachementRecipe.java:87) ~[?:1.3-13] {re:classloading}
	at vazkii.akashictome.AttachementRecipe.matches(AttachementRecipe.java:26) ~[?:1.3-13] {re:classloading}
	at vazkii.akashictome.AttachementRecipe.func_77569_a(AttachementRecipe.java:12) ~[?:1.3-13] {re:classloading}
	at net.minecraft.item.crafting.IRecipeType.func_222148_a(SourceFile:29) ~[?:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeManager.lambda$getRecipe$2(RecipeManager.java:81) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_212] {}
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1649) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_212] {}
	at net.minecraft.item.crafting.RecipeManager.func_215371_a(RecipeManager.java:82) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.GridNetworkNode.onCraftingMatrixChanged(GridNetworkNode.java:368) ~[?:1.8.3] {re:classloading}
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.GridNetworkNode$1.func_75130_a(GridNetworkNode.java:93) ~[?:1.8.3] {re:classloading}
	at net.minecraft.inventory.CraftingInventory.func_70299_a(SourceFile:70) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.raoulvdberge.refinedstorage.apiimpl.network.grid.CraftingGridBehavior.onRecipeTransfer(CraftingGridBehavior.java:137) ~[?:1.8.3] {re:classloading}
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.GridNetworkNode.onRecipeTransfer(GridNetworkNode.java:386) ~[?:1.8.3] {re:classloading}
	at com.raoulvdberge.refinedstorage.network.grid.GridTransferMessage.lambda$handle$0(GridTransferMessage.java:84) ~[?:1.8.3] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at com.raoulvdberge.refinedstorage.network.grid.GridTransferMessage.handle(GridTransferMessage.java:79) ~[?:1.8.3] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,pl:mixin:APP:mixins.dcintegration.json:MixinNetHandlerPlayServer,pl:mixin:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.19.107-Unraid
	Java Version: 1.8.0_212, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 1328778840 bytes (1267 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:+UseG1GC -Xms2G -Xmx2G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.47.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.47.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.47.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.47.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.47.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.47
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		doubledoors_1.15-2.0.jar Double Doors {doubledoors@2.0 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		equaldragons-1.2.jar Equal Dragons {equaldragons@1.2 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Mekanism-1.15.2-9.10.1.414.jar Mekanism {mekanism@9.10.1 DONE}
		caelus-FORGE-1.15.2-2.0-beta2.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta2 DONE}
		reap-1.12.3.jar Reap Mod {reap@1.12.3 DONE}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 DONE}
		Neat 1.6-20.jar Neat {neat@1.6-20 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		branders-lampblockmod-1.15.2-1.1.2.jar Lamp Block Mod {lampblockmod@1.1.2 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.8.jar The Endergetic Expansion {endergetic@1.2.8 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha DONE}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha DONE}
		xnet-1.15-2.0.2-alpha.jar XNet {xnet@1.15-2.0.2-alpha DONE}
		DarkUtilities-1.15.2-3.0.5.jar Dark Utilities {darkutils@3.0.5 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		environmentalcreepers-forge-1.15.2-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 DONE}
		MekanismGenerators-1.15.2-9.10.1.414.jar Mekanism: Generators {mekanismgenerators@9.10.1 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		JEITweaker-1.0.0.jar JEI Tweaker {jeitweaker@1.0.0 DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		CraftTweaker-1.15.2-6.0.0.17.jar CraftTweaker {crafttweaker@6.0.0.17 DONE}
		forge-1.15.2-31.1.47-universal.jar Forge {forge@31.1.47 DONE}
		dcintegration-1.1.14-1.15.jar Discord Integration {dcintegration@1.1.14 DONE}
		refinedstorage-1.8.3.jar Refined Storage {refinedstorage@1.8.3 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		forge-1.15.2-31.1.47-server.jar Minecraft {minecraft@1.15.2 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 DONE}
		finallyfarmabledyes-1.15.2-1.1.0.0.jar Finally Farmable Dyes {finallyfarmabledyes@1.1.0.0 DONE}
		morevanillalib-1.15.2-1.2.2.jar MoreVanillaLib {morevanillalib@1.2.2 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		ironfurnaces-1.15.2-2.0.3.jar Iron Furnaces {ironfurnaces@2.0.3 DONE}
		NetherGen+[1.15.2]-1.0.1.jar NetherGen+ {nethergenplus@1.0.1 DONE}
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		gravestone-1.17.4.jar Gravestone Mod {gravestone@1.17.4 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 DONE}
		Quark-r2.1-235.jar Quark {quark@r2.1-235 DONE}
		performant-1.15-2.09m.jar Performant {performant@2.09m DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		vanillahammers-1.15.2-2.1.jar Vanilla Hammers {vanillahammers@2.1 DONE}
		InventoryHud_1.15.1-1.15.2.forge-2.6.1.jar Inventory HUD+(Forge edition) {inventoryhud@2.6.1 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		Ma-Essentials-1.15.2-3.0.3.jar Ma Essentials {ma-essentials@1.15.2-3.0.3 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 DONE}
	Player Count: 1 / 20; [ServerPlayerEntity['xorinzor'/149, l='world', x=-315.09, y=84.00, z=-100.35]]
	Data Packs: vanilla, mod:aiimprovements (incompatible), mod:akashictome (incompatible), mod:angelring (incompatible), mod:appleskin (incompatible), mod:aquaculture, mod:autoreglib (incompatible), mod:betteradvancements (incompatible), mod:bookshelf (incompatible), mod:bowinfinityfix (incompatible), mod:buzzierbees, mod:caelus (incompatible), mod:clumps (incompatible), mod:cookingforblockheads (incompatible), mod:curios (incompatible), mod:curiouselytra (incompatible), mod:darkutils (incompatible), mod:dcintegration, mod:dimdungeons, mod:doubledoors (incompatible), mod:enchdesc (incompatible), mod:endergetic (incompatible), mod:equaldragons, mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fastleafdecay, mod:forge (incompatible), mod:goldenhopper, mod:industrialforegoing (incompatible), mod:inventoryhud, mod:ironchest, mod:ironfurnaces (incompatible), mod:jei (incompatible), mod:lampblockmod (incompatible), mod:mcjtylib (incompatible), mod:morpheus (incompatible), mod:nethergenplus, mod:netherportalfix (incompatible), mod:performant (incompatible), mod:phosphor, mod:placebo (incompatible), mod:quark, mod:reap, mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:rftoolsbase (incompatible), mod:titanium (incompatible), mod:valhelsia_structures (incompatible), mod:waila (incompatible), mod:waystones (incompatible), mod:wstweaks (incompatible), mod:xnet (incompatible), mod:journeymap (incompatible), mod:lollipop (incompatible), mod:powah (incompatible), mod:neat (incompatible), mod:reauth (incompatible), mod:xlfoodmod, mod:attributefix (incompatible), mod:ma-essentials (incompatible), mod:randompatches (incompatible), mod:crafttweaker (incompatible), mod:jeitweaker, mod:mekanism, mod:simplechunkloaders (incompatible), mod:valkyrielib (incompatible), mod:mekanismgenerators, mod:environmentalcreepers (incompatible), mod:gravestone, mod:finallyfarmabledyes, mod:jeresources (incompatible), mod:morevanillalib, mod:vanillahammers
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Buuz135** [comment]
Update Industrial Foregoing
